name: CodSpeed Benchmarks

on:
  pull_request:
    branches: [main, master]
  push:
    branches: [main, master]
  # `workflow_dispatch` allows CodSpeed to trigger backtest
  # performance analysis in order to generate initial data.
  workflow_dispatch:

jobs:
  benchmark:
    name: Run CodSpeed Benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]
          pip install pytest-codspeed eth-utils "eth-hash[pycryptodome]"
      - name: Run CodSpeed & Save Output
        uses: CodSpeedHQ/action@v3
        with:
          run: pytest --codspeed benchmarks/ | tee codspeed_output.txt
      - name: Parse CodSpeed Output
        run: python scripts/parse_codspeed_output.py codspeed_output.txt codspeed_results.json
      - name: Compare CodSpeed Results
        run: python scripts/compare_codspeed_results.py codspeed_results.json codspeed_diff.json
      - name: Upload CodSpeed Results
        uses: actions/upload-artifact@v4
        with:
          name: codspeed-results
          path: codspeed_results.json
      - name: Upload CodSpeed Diff
        uses: actions/upload-artifact@v4
        with:
          name: codspeed-diff
          path: codspeed_diff.json
      - name: Post CodSpeed Diff as PR Comment
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const diff = JSON.parse(fs.readFileSync('codspeed_diff.json', 'utf8'));
            let body = '### CodSpeed Benchmark Diff\n\n';
            for (const [func, data] of Object.entries(diff)) {
              if (data.percent_change !== null && data.percent_change !== undefined) {
                body += `- \`${func}\`: ${data.reference_mean} → ${data.faster_mean} ${data.unit} (${data.percent_change.toFixed(2)}%)\n`;
              } else if (data.note) {
                body += `- \`${func}\`: ${data.note}\n`;
              }
            }
            github.rest.issues.createComment({
              ...context.repo,
              issue_number: context.issue.number,
              body
            });
        if: github.event_name == 'pull_request'
