name: CodSpeed Benchmarks

on:
  pull_request:
    branches: [main, master]
  push:
    branches: [main, master]
  # `workflow_dispatch` allows CodSpeed to trigger backtest
  # performance analysis in order to generate initial data.
  workflow_dispatch:

jobs:
  benchmark:
    name: Run CodSpeed Benchmarks
    runs-on: codspeed-macro
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]
          pip install pytest-codspeed eth-utils "eth-hash[pycryptodome]"
      - name: Run CodSpeed
        uses: CodSpeedHQ/action@v3
        with:
          run: pytest --codspeed benchmarks/
