name: CodSpeed Benchmarks

on:
  pull_request:
    branches: [main, master]
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  benchmark:
    name: Run Benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]
          pip install pytest-codspeed pytest-benchmark eth-utils "eth-hash[pycryptodome]"
      - name: Run CodSpeed
        uses: CodSpeedHQ/action@v3
        with:
          run: pytest --codspeed -k "test_faster_" benchmarks/
      - name: Run Pytest Benchmark & Save Output
        run: pytest --benchmark-only --benchmark-json=benchmark.json benchmarks/
      - name: Upload Pytest Benchmark Results
        uses: actions/upload-artifact@v4
        with:
          name: pytest-benchmark-results
          path: benchmark.json
      - name: Parse Pytest Benchmark Output
        run: python scripts/benchmark/parse_benchmark_output.py benchmark.json pytest_benchmark_results.json
      - name: Compare Pytest Benchmark Results
        run: python scripts/benchmark/compare_benchmark_results.py pytest_benchmark_results.json pytest_benchmark_diff.json
      - name: Upload Pytest Benchmark Diff
        uses: actions/upload-artifact@v4
        with:
          name: pytest-benchmark-diff
          path: pytest_benchmark_diff.json
      - name: Post Pytest Benchmark Diff as PR Comment
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const diff = JSON.parse(fs.readFileSync('pytest_benchmark_diff.json', 'utf8'));
            let body = '### Pytest Benchmark Diff\n\n';
            // Get repo and branch info from context
            const repo = `${context.repo.owner}/${context.repo.repo}`;
            const branch = context.payload.pull_request ? context.payload.pull_request.head.ref : context.ref.replace('refs/heads/', '');
            for (const [submodule, groupDiffs] of Object.entries(diff)) {
              // Convert submodule name to benchmark file path (e.g., faster_eth_utils.abi -> benchmarks/test_abi_benchmarks.py)
              let filePath = "unknown";
              const m = submodule.match(/^faster_eth_utils\.(.+)$/);
              if (m) {
                filePath = `benchmarks/test_${m[1]}_benchmarks.py`;
              }
              const url = `https://github.com/${repo}/blob/${branch}/${filePath}`;
              body += `#### [${submodule}](${url})\n`;
              body += '| Function | Reference Mean | Faster Mean | % Change | Faster | Note |\n';
              body += '|----------|---------------|-------------|----------|--------|------|\n';
              for (const [group, data] of Object.entries(groupDiffs).sort(([a], [b]) => a.localeCompare(b))) {
                if (data.percent_change !== null && data.percent_change !== undefined) {
                  let emoji = '➖';
                  if (data.percent_change > 0) emoji = '✅';
                  else if (data.percent_change < 0) emoji = '❌';
                  body += `| \`${group}\` | ${data.reference_mean} | ${data.faster_mean} | ${data.percent_change.toFixed(2)}% | ${emoji} | |\n`;
                } else if (data.note) {
                  body += `| \`${group}\` |  |  |  |  | ${data.note} |\n`;
                }
              }
              body += '\n';
            }
            github.rest.issues.createComment({
              ...context.repo,
              issue_number: context.issue.number,
              body
            });
        if: github.event_name == 'pull_request'
