name: CodSpeed Benchmarks

on:
  pull_request:
    branches: [main, master]
  push:
    branches: [main, master]

jobs:
  benchmark:
    name: Run CodSpeed Benchmarks
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]
          pip install pytest-codspeed
          pip install "eth-hash[pycryptodome]"
      - name: Run CodSpeed
        uses: CodSpeedHQ/action@v2
        with:
          run: pytest --codspeed benchmarks/
