name: CodSpeed Benchmarks

on:
  pull_request:
    branches: [main, master]
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  benchmark:
    name: Run CodSpeed Benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]
          pip install pytest-codspeed pytest-benchmark eth-utils "eth-hash[pycryptodome]"
      - name: Run CodSpeed & Save Output
        uses: CodSpeedHQ/action@v3
        with:
          run: pytest --codspeed -v benchmarks/ | tee codspeed_output.txt
      - name: Run Pytest Benchmark & Save Output
        run: pytest --benchmark-only --benchmark-json=benchmark.json benchmarks/
      - name: Upload Pytest Benchmark Results
        uses: actions/upload-artifact@v4
        with:
          name: pytest-benchmark-results
          path: benchmark.json
      - name: Parse Pytest Benchmark Output
        run: python scripts/benchmark/parse_benchmark_output.py benchmark.json pytest_benchmark_results.json
      - name: Compare Pytest Benchmark Results
        run: python scripts/benchmark/compare_benchmark_results.py pytest_benchmark_results.json pytest_benchmark_diff.json
      - name: Upload Pytest Benchmark Diff
        uses: actions/upload-artifact@v4
        with:
          name: pytest-benchmark-diff
          path: pytest_benchmark_diff.json
      - name: Post Pytest Benchmark Diff as PR Comment
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const diff = JSON.parse(fs.readFileSync('pytest_benchmark_diff.json', 'utf8'));
            let body = '### Pytest Benchmark Diff\n\n';
            for (const [group, data] of Object.entries(diff)) {
              if (data.percent_change !== null && data.percent_change !== undefined) {
                body += `- \`${group}\`: ${data.reference_mean} → ${data.faster_mean} ${data.unit} (${data.percent_change.toFixed(2)}%)\n`;
              } else if (data.note) {
                body += `- \`${group}\`: ${data.note}\n`;
              }
            }
            github.rest.issues.createComment({
              ...context.repo,
              issue_number: context.issue.number,
              body
            });
        if: github.event_name == 'pull_request'
