name: CodSpeed Benchmarks

on:
  pull_request:
    branches: [main, master]
    paths:
      - '**.py'
      - '.github/workflows/codspeed.yaml'
      - 'pyproject.toml'
      - 'setup.py'
  push:
    branches: [main, master]
    paths:
      - '**.py'
      - '.github/workflows/codspeed.yaml'
      - 'pyproject.toml'
      - 'setup.py'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  benchmark:
    name: Run Benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip
          cache-dependency-path: |
            setup.py
            pyproject.toml
            
      - name: Cache .mypy_cache
        uses: actions/cache@v4
        with:
          path: .mypy_cache
          key: mypy-cache-${{ runner.os }}-${{ hashFiles('**/*.py', 'pyproject.toml') }}
            
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]
          pip install pytest-codspeed eth-utils "eth-hash[pycryptodome]"
          
      - name: Run CodSpeed
        uses: CodSpeedHQ/action@v3
        with:
          run: pytest --codspeed -k "test_faster_" benchmarks/
